package main

import (
	"fmt"

	"github.com/spf13/cobra"
)

// ── export ────────────────────────────────────────────────────────────────────

var exportCmd = &cobra.Command{
	Use:   "export",
	Short: "Print a sanitized config template (no secrets) for sharing with teammates",
	RunE: func(cmd *cobra.Command, args []string) error {
		if cfg == nil {
			return fmt.Errorf("%s", ct("cli.error.no_config_loaded"))
		}

		// YAML syntax helpers — only colorize on interactive terminals.
		yKey := func(s string) string { return styleMapVia.Render(s) }
		yStr := func(s string) string { return styleStatusIP.Render(s) }
		yNum := func(s string) string { return styleStatusTime.Render(s) }
		yComment := func(s string) string { return styleDim.Render(s) }
		ySection := func(s string) string { return styleGold.Render(s) }

		p := func(indent, key, val string) {
			fmt.Printf("%s%s: %s\n", indent, yKey(key), yStr(val))
		}
		pNum := func(indent, key string, val int) {
			fmt.Printf("%s%s: %s\n", indent, yKey(key), yNum(fmt.Sprintf("%d", val)))
		}
		pComment := func(indent, key, val, comment string) {
			fmt.Printf("%s%s: %s  %s\n", indent, yKey(key), yStr(val), yComment("# "+comment))
		}

		fmt.Println(yComment("# Kongtrol config template — generated by 'kongtrol export'"))
		fmt.Println(yComment("# Passwords and keys are redacted. Run 'kongtrol init' on the target machine"))
		fmt.Println(yComment("# to store credentials in the OS keychain."))
		fmt.Println()
		fmt.Println(ySection("vpns") + yKey(":"))
		for name, v := range cfg.VPNs {
			fmt.Printf("  %s:\n", styleBright.Render(name))
			p("    ", "type", v.Type)
			if v.Version != "" {
				p("    ", "version", v.Version)
			}
			if v.Host != "" {
				p("    ", "host", v.Host)
			}
			if v.Port != 0 {
				pNum("    ", "port", v.Port)
			}
			if v.TunnelName != "" {
				p("    ", "tunnel_name", v.TunnelName)
			}
			if v.ConfigFile != "" {
				p("    ", "config", v.ConfigFile)
			}
			if v.Server != "" {
				p("    ", "server", v.Server)
			}
			if v.Protocol != "" {
				p("    ", "protocol", v.Protocol)
			}
			if v.Priority != 0 {
				pNum("    ", "priority", v.Priority)
			}
			fmt.Printf("    %s:\n", yKey("auth"))
			p("      ", "method", v.Auth.Method)
			if v.Auth.Cert != "" {
				p("      ", "cert", v.Auth.Cert)
			}
			if v.Auth.Key != "" {
				p("      ", "key", v.Auth.Key)
			}
			if v.Auth.Username != "" {
				p("      ", "username", v.Auth.Username)
			}
			if v.Auth.PasswordKeychain != "" {
				pComment("      ", "password_keychain", v.Auth.PasswordKeychain, "store via: kongtrol init")
			}
			if v.Auth.UsernameKeychain != "" {
				pComment("      ", "username_keychain", v.Auth.UsernameKeychain, "store via: kongtrol init")
			}
		}
		if len(cfg.Policies) > 0 {
			fmt.Println()
			fmt.Println(ySection("policies") + yKey(":"))
			for _, pol := range cfg.Policies {
				fmt.Printf("  - %s: %s\n", yKey("name"), yStr(pol.Name))
				if len(pol.Match.IPRanges) > 0 {
					fmt.Printf("    %s:\n      %s: %s\n", yKey("match"), yKey("ip_ranges"), yNum(fmt.Sprintf("%v", pol.Match.IPRanges)))
				}
				if len(pol.Match.Domains) > 0 {
					fmt.Printf("    %s:\n      %s: %s\n", yKey("match"), yKey("domains"), yNum(fmt.Sprintf("%v", pol.Match.Domains)))
				}
				if len(pol.Match.Apps) > 0 {
					fmt.Printf("    %s:\n      %s: %s\n", yKey("match"), yKey("apps"), yNum(fmt.Sprintf("%v", pol.Match.Apps)))
				}
				fmt.Printf("    %s: %s\n", yKey("via"), yStr(pol.Via))
			}
		}
		if len(cfg.Groups) > 0 {
			fmt.Println()
			fmt.Println(ySection("groups") + yKey(":"))
			for name, g := range cfg.Groups {
				fmt.Printf("  %s:\n    %s: %s\n", styleBright.Render(name), yKey("profiles"), yNum(fmt.Sprintf("%v", g.Profiles)))
			}
		}
		return nil
	},
}

var versionCmd = &cobra.Command{
	Use:   "version",
	Short: "Show CLI version",
	Run: func(cmd *cobra.Command, args []string) {
		// Piped / quiet output stays a bare, parseable version string.
		if outputQuiet || outputPlain || !isTerminal() {
			fmt.Println(version)
			return
		}
		PrintHeader(version)
	},
}
